import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    overlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.4)',
        justifyContent: 'flex-end',
    },
    dismiss: {
        flex: 1,
    },
    sheetContainer: {
        width: '100%',
        height: 384,
        borderTopLeftRadius: 12,
        borderTopRightRadius: 12,
        borderTopWidth: 1,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -10 },
        shadowOpacity: 0.15,
        shadowRadius: 20,
        elevation: 20,
        overflow: 'hidden',
    },
    sheetLight: {
        backgroundColor: 'white',
        borderColor: 'rgba(236, 73, 19, 0.1)',
    },
    tabsWrapper: {
        paddingVertical: 8,
        paddingHorizontal: 16,
    },
    tabsContent: {
        gap: 8,
    },
    tabChip: {
        height: 32,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 12,
        borderRadius: 9999,
        gap: 6,
    },
    tabChipActive: {
        backgroundColor: '#ec4913',
        shadowColor: '#ec4913',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 4,
    },
    tabChipInactiveLight: {
        backgroundColor: '#f1f5f9',
    },
    tabLabel: {
        fontSize: 12,
        fontWeight: '600',
    },
    tabLabelActive: {
        color: 'white',
    },
    tabLabelInactiveLight: {
        color: '#475569',
    },
    contentScroll: {
        flex: 1,
    },
    detailContainer: {
        paddingHorizontal: 16,
        paddingTop: 4,
    },
    productHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 16,
        paddingVertical: 8,
    },
    avatarImage: {
        height: 64,
        width: 64,
        borderRadius: 32,
        borderWidth: 2,
        borderColor: 'white',
    },
    sliderWrapper: {
        width: 64,
        alignItems: 'center',
        gap: 4,
    },
    imageList: {
        width: 64,
        height: 64,
        borderRadius: 32,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    paginationDots: {
        flexDirection: 'row',
        gap: 4,
        justifyContent: 'center',
        marginTop: 2,
    },
    dot: {
        width: 4,
        height: 4,
        borderRadius: 2,
    },
    dotActive: {
        backgroundColor: '#ec4913',
        width: 10,
    },
    dotInactive: {
        backgroundColor: '#cbd5e1',
    },
    headerInfo: {
        flex: 1,
        justifyContent: 'center',
    },
    productTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        lineHeight: 22,
    },
    productDesc: {
        fontSize: 14,
        fontWeight: '400',
        lineHeight: 18,
        marginTop: 2,
    },
    textDark: { color: '#0f172a' },
    textGrayDark: { color: '#64748b' },
    priceChipsContainer: {
        flexDirection: 'row',
        gap: 8,
        paddingVertical: 12,
        borderTopWidth: 1,
        marginVertical: 4,
    },
    borderLight: { borderColor: '#f1f5f9' },
    sizeChip: {
        flex: 1,
        height: 54,
        padding: 8,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
    },
    sizeChipActive: {
        backgroundColor: 'rgba(236, 73, 19, 0.05)',
        borderColor: '#ec4913',
        borderWidth: 2,
    },
    sizeChipInactiveLight: {
        borderColor: '#e2e8f0',
        backgroundColor: 'transparent',
    },
    sizeLabel: {
        fontSize: 10,
        textTransform: 'uppercase',
        fontWeight: 'bold',
    },
    sizeLabelActive: { color: '#ec4913' },
    sizeLabelInactive: { color: '#94a3b8' },
    sizePrice: {
        fontSize: 14,
        fontWeight: 'bold',
    },
    gridRow: {
        flexDirection: 'row',
        gap: 8,
        marginBottom: 80,
    },
    gridBtn: {
        flex: 1,
        paddingVertical: 10,
        paddingHorizontal: 4,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'space-between',
        elevation: 2,
        backgroundColor: 'white',
    },
    gridTextCenter: {
        alignItems: 'center',
        marginTop: 4,
    },
    gridTitle: {
        fontSize: 12,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    gridSubText: {
        fontSize: 11,
        fontWeight: '500',
        color: '#ec4913',
        marginTop: 2,
        textAlign: 'center',
    },
    bottomActionBar: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        paddingVertical: 16,
        paddingHorizontal: 16,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        borderTopWidth: 1,
    },
    actionBarLight: { backgroundColor: 'white', borderColor: '#f1f5f9' },
    priceSectionLeft: {
        flex: 1,
        alignItems: 'flex-start',
        justifyContent: 'center',
    },
    currencyText: {
        fontSize: 12,
        fontWeight: 'bold',
        textAlign: 'left',
        lineHeight: 14,
    },
    counterContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 2,
        borderRadius: 9999,
        height: 48,
        backgroundColor: '#f1f5f9',
    },
    counterLight: { backgroundColor: '#f1f5f9' },
    counterBtn: {
        width: 40,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 20,
    },
    counterBtnAdd: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
        backgroundColor: 'white',
    },
    counterBtnAddLight: { backgroundColor: 'white' },
    counterText: {
        width: 32,
        textAlign: 'center',
        fontWeight: 'bold',
        fontSize: 14,
    },
    addToCartBtn: {
        flex: 1.5,
        height: 48,
        backgroundColor: '#ec4913',
        borderRadius: 24,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#ec4913',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
    },
    buyBtn: {
        flex: 1.2,
        height: 48,
        backgroundColor: '#ec4913',
        borderRadius: 16,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 4,
        shadowColor: '#ec4913',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
    },
    btnText: {
        color: 'white',
        fontSize: 11,
        fontWeight: 'bold',
    },
    placeholderContent: {
        height: 200,
        alignItems: 'center',
        justifyContent: 'center',
    },
    gridList: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        paddingHorizontal: 16,
        gap: 16,
        paddingTop: 8,
    },
    extraItem: {
        width: '21%',
        alignItems: 'center',
        marginBottom: 20,
    },
    extraIconContainer: {
        width: 64,
        height: 64,
        borderRadius: 16,
        backgroundColor: 'rgba(236, 73, 19, 0.05)',
        alignItems: 'center',
        justifyContent: 'center',
        position: 'relative',
        borderWidth: 2,
        borderColor: 'transparent',
    },
    extraIconSelected: {
        borderColor: '#ec4913',
    },
    selectedBadge: {
        position: 'absolute',
        top: -4,
        right: -4,
        backgroundColor: '#ec4913',
        width: 16,
        height: 16,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    selectedBadgeText: {
        color: 'white',
        fontSize: 8,
        fontWeight: 'bold',
    },
    extraTextCenter: {
        alignItems: 'center',
        marginTop: 8,
    },
    extraName: {
        fontSize: 11,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    extraPrice: {
        fontSize: 10,
        color: '#ec4913',
        fontWeight: '500',
    },
    drinksContainer: {
        paddingHorizontal: 16,
        paddingTop: 8,
    },
    drinkRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#f1f5f9',
    },
    drinkLeft: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    checkbox: {
        width: 20,
        height: 20,
        borderRadius: 4,
        borderWidth: 1,
        borderColor: '#cbd5e1',
        alignItems: 'center',
        justifyContent: 'center',
    },
    checkboxActive: {
        backgroundColor: '#ec4913',
        borderColor: '#ec4913',
    },
    drinkName: {
        fontSize: 14,
        fontWeight: '500',
        marginLeft: 12,
    },
    drinkPrice: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#ec4913',
    },
    deliveryContainer: {
        paddingHorizontal: 16,
        paddingTop: 8,
        flex: 1,
    },
    infoGrid4: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 16,
    },
    infoBtnLarge: {
        flex: 1,
        backgroundColor: 'white',
        borderRadius: 16,
        padding: 12,
        borderWidth: 1,
        borderColor: '#f1f5f9',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        minHeight: 80,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 2,
    },
    infoBtnText: {
        marginTop: 8,
    },
    infoBtnTitle: {
        fontSize: 13,
        fontWeight: 'bold',
    },
    infoBtnSubText: {
        fontSize: 9,
        color: '#ec4913',
        fontWeight: '500',
        marginTop: 2,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        width: '50%',
        paddingBottom: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#cbd5e1',
        marginBottom: 16,
    },
    sectionHeaderText: {
        fontSize: 10,
        fontWeight: 'bold',
        color: '#94a3b8',
        textTransform: 'uppercase',
    },
    deliveryTypeGrid: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 80,
    },
    deliveryTypeBtn: {
        flex: 1,
        backgroundColor: 'rgba(236, 73, 19, 0.03)',
        borderRadius: 16,
        padding: 12,
        borderWidth: 2,
        borderColor: 'transparent',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        minHeight: 100,
    },
    deliveryTypeActive: {
        borderColor: '#ec4913',
        backgroundColor: 'rgba(236, 73, 19, 0.05)',
    },
    deliveryTypeText: {
        marginTop: 8,
    },
    deliveryTypeTitle: {
        fontSize: 13,
        fontWeight: 'bold',
    },
    deliveryTypeSubText: {
        fontSize: 9,
        color: '#94a3b8',
        fontWeight: '500',
        marginTop: 2,
    },
});
